// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Farm_and_Crop_Yeild_Management_System.Models;

#nullable disable

namespace Smart_Farm_and_Crop_Yeild_Management_System.Migrations
{
    [DbContext(typeof(SmartFarmDbContext))]
    [Migration("20260721043553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.AdminProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("AdminProfile");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            Department = "IT",
                            EmployeeId = "ADMIN001",
                            FirstName = "System",
                            LastName = "Administrator",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Agronomist", b =>
                {
                    b.Property<int>("AgronomistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgronomistId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AgronomistId");

                    b.HasIndex("MobileNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Agronomist_MobileNumber");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Agronomist_UserId");

                    b.ToTable("Agronomist");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.AgronomistAnalysis", b =>
                {
                    b.Property<int>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisId"));

                    b.Property<int>("AgronomistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CropAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiseaseAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PestAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("SoilAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("WeatherAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AnalysisId");

                    b.HasIndex("AgronomistId");

                    b.HasIndex("RequestId");

                    b.ToTable("AgronomistAnalysis");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("OfficerId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerId"));

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BuyerId");

                    b.HasIndex("UserId");

                    b.ToTable("Buyer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.BuyerComplaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("ComplaintType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ComplaintId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OrderId");

                    b.ToTable("BuyerComplaint");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CooperativeManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("CooperativeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("CooperativeManager");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CropId");

                    b.ToTable("Crop");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropCycle", b =>
                {
                    b.Property<int>("CropCycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropCycleId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpectedHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SowingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CropCycleId");

                    b.HasIndex("CropId");

                    b.HasIndex("PlotId");

                    b.ToTable("CropCycle");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropListing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<decimal>("AvailableQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<int>("HarvestId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ListedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchasedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ListingId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("HarvestId");

                    b.ToTable("CropListing");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropMonitoring", b =>
                {
                    b.Property<int>("MonitoringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonitoringId"));

                    b.Property<int>("CropCycleId")
                        .HasColumnType("int");

                    b.Property<string>("CropHealth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GrowthStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlantHeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MonitoringId");

                    b.HasIndex("CropCycleId");

                    b.ToTable("CropMonitoring");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GST")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("HarvestId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ListingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("HarvestId");

                    b.HasIndex("ListingId");

                    b.ToTable("CropOrder");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CultivationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<decimal>("CultivationArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<decimal>("MoistureLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoilPH")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4, 2)");

                    b.Property<DateTime>("SowingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("RequestId");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("PlotId");

                    b.ToTable("CultivationRequest");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Taluka")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Village")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farm");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Taluka")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Village")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FarmerId");

                    b.HasIndex("UserId");

                    b.ToTable("Farmer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldOfficer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<string>("AssignedDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssignedTaluka")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OfficerId");

                    b.HasIndex("UserId");

                    b.ToTable("FieldOfficer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldOfficerAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<int>("FieldOfficerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("AssignmentId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("FieldOfficerUserId");

                    b.ToTable("FieldOfficerAssignment");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldVisit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VisitId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("PlotId");

                    b.ToTable("FieldVisit");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Harvest", b =>
                {
                    b.Property<int>("HarvestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarvestId"));

                    b.Property<decimal>("ActualQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HarvestId");

                    b.HasIndex("CropCycleId");

                    b.ToTable("Harvest");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.HarvestDecision", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DecisionId"));

                    b.Property<int>("AgronomistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CropHealthAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiseaseAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HarvestId")
                        .HasColumnType("int");

                    b.Property<string>("PestAnalysis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("DecisionId");

                    b.HasIndex("AgronomistId");

                    b.HasIndex("HarvestId");

                    b.ToTable("HarvestDecision");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", b =>
                {
                    b.Property<int>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlotId"));

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AreaUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("IrrigationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PlotCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlotId");

                    b.HasIndex("FarmId");

                    b.ToTable("LandPlot");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.PestCase", b =>
                {
                    b.Property<int>("PestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PestCaseId"));

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CropCycleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FarmerResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FarmerResponseToReport")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldReport")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FieldVisitCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FieldVisitRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReportUploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PestCaseId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("CropCycleId");

                    b.ToTable("PestCase");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ExportedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExported")
                        .HasColumnType("bit");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedModule")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Farmer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Buyer"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Agronomist"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Field Officer"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "Cooperative Manager"
                        });
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.SensorReading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<decimal>("ElectricalConductivity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nitrogen")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OrganicCarbon")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("Phosphorus")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<decimal>("Potassium")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SoilMoisture")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SoilPH")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("ReadingId");

                    b.HasIndex("PlotId");

                    b.ToTable("SensorReading");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.SupportQuery", b =>
                {
                    b.Property<int>("QueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueryId"));

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AgronomistRecommendation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("FieldObservation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImprovementActions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImprovementExpectedBenefits")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImprovementStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RecommendationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QueryId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("PlotId");

                    b.ToTable("SupportQuery");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@smartfarm.com",
                            IsActive = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            PasswordHash = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.VisitPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitPhoto");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<bool>("NotifyWhenAvailable")
                        .HasColumnType("bit");

                    b.HasKey("WishlistId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldPhoto", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("YieldId")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("YieldId");

                    b.ToTable("YieldPhoto");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldRecord", b =>
                {
                    b.Property<int>("YieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YieldId"));

                    b.Property<decimal?>("Area")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedYield")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("YieldId");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("PlotId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("YieldRecord");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldValidation", b =>
                {
                    b.Property<int>("ValidationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValidationId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldOfficerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YieldId")
                        .HasColumnType("int");

                    b.HasKey("ValidationId");

                    b.HasIndex("FieldOfficerUserId");

                    b.HasIndex("YieldId");

                    b.ToTable("YieldValidation");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.AdminProfile", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AdminProfile_Users_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Agronomist", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Agronomist_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.AgronomistAnalysis", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Agronomist", "Agronomist")
                        .WithMany()
                        .HasForeignKey("AgronomistId")
                        .IsRequired()
                        .HasConstraintName("FK_AgronomistAnalysis_Agronomist");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.CultivationRequest", "CultivationRequest")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK_AgronomistAnalysis_Request");

                    b.Navigation("Agronomist");

                    b.Navigation("CultivationRequest");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Assignment", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Farmer");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Buyer", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany("Buyers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Buyer__UserId__44FF419A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.BuyerComplaint", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropOrder", "CropOrder")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("CropOrder");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CooperativeManager", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropCycle", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Crop", "Crop")
                        .WithMany("CropCycles")
                        .HasForeignKey("CropId")
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", "LandPlot")
                        .WithMany("CropCycles")
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("LandPlot");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropListing", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Harvest", "Harvest")
                        .WithMany("CropListings")
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropMonitoring", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropCycle", "CropCycle")
                        .WithMany("CropMonitorings")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropCycle");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropOrder", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .IsRequired()
                        .HasConstraintName("FK_CropOrder_Buyer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .IsRequired()
                        .HasConstraintName("FK_CropOrder_Farmer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Harvest", "Harvest")
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .HasConstraintName("FK_CropOrder_Harvest");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropListing", "CropListing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_CropOrder_CropListing");

                    b.Navigation("Buyer");

                    b.Navigation("CropListing");

                    b.Navigation("Farmer");

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CultivationRequest", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .IsRequired()
                        .HasConstraintName("FK_CultivationRequest_Crop");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .IsRequired()
                        .HasConstraintName("FK_CultivationRequest_Farm");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .IsRequired()
                        .HasConstraintName("FK_CultivationRequest_Farmer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", "LandPlot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .IsRequired()
                        .HasConstraintName("FK_CultivationRequest_LandPlot");

                    b.Navigation("Crop");

                    b.Navigation("Farm");

                    b.Navigation("Farmer");

                    b.Navigation("LandPlot");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany("Farmers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Farmer__UserId__403A8C7D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldOfficer", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldOfficerAssignment", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .IsRequired()
                        .HasConstraintName("FK_FOA_Farmer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "FieldOfficer")
                        .WithMany()
                        .HasForeignKey("FieldOfficerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_FOA_Users");

                    b.Navigation("Farmer");

                    b.Navigation("FieldOfficer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldVisit", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId")
                        .IsRequired()
                        .HasConstraintName("FK_FieldVisit_Officer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .IsRequired()
                        .HasConstraintName("FK_FieldVisit_Farmer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", "LandPlot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .HasConstraintName("FK_FieldVisit_LandPlot");

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Farmer");

                    b.Navigation("LandPlot");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Harvest", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropCycle", "CropCycle")
                        .WithMany("Harvests")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropCycle");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.HarvestDecision", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Agronomist", "Agronomist")
                        .WithMany()
                        .HasForeignKey("AgronomistId")
                        .IsRequired()
                        .HasConstraintName("FK_HarvestDecision_Agronomist");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Harvest", "Harvest")
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .IsRequired()
                        .HasConstraintName("FK_HarvestDecision_Harvest");

                    b.Navigation("Agronomist");

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", "Farm")
                        .WithMany("LandPlots")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Notification", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.PestCase", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropCycle", "CropCycle")
                        .WithMany("PestCases")
                        .HasForeignKey("CropCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedOfficer");

                    b.Navigation("CropCycle");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.SensorReading", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.SupportQuery", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", "LandPlot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Farm");

                    b.Navigation("Farmer");

                    b.Navigation("LandPlot");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.VisitPhoto", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldVisit", "FieldVisit")
                        .WithMany("VisitPhotos")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VisitPhoto_FieldVisit");

                    b.Navigation("FieldVisit");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Wishlist", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId");

                    b.Navigation("Buyer");

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldPhoto", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldRecord", "YieldRecord")
                        .WithMany("YieldPhotos")
                        .HasForeignKey("YieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_YieldPhoto_YieldRecord");

                    b.Navigation("YieldRecord");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldRecord", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .HasConstraintName("FK_YieldRecord_Crop");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .IsRequired()
                        .HasConstraintName("FK_YieldRecord_Farmer");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", "LandPlot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .HasConstraintName("FK_YieldRecord_LandPlot");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .HasConstraintName("FK_YieldRecord_Users");

                    b.Navigation("Crop");

                    b.Navigation("Farmer");

                    b.Navigation("LandPlot");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldValidation", b =>
                {
                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", "FieldOfficer")
                        .WithMany()
                        .HasForeignKey("FieldOfficerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_YieldValidation_Users");

                    b.HasOne("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldRecord", "YieldRecord")
                        .WithMany("YieldValidations")
                        .HasForeignKey("YieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_YieldValidation_YieldRecord");

                    b.Navigation("FieldOfficer");

                    b.Navigation("YieldRecord");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Crop", b =>
                {
                    b.Navigation("CropCycles");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.CropCycle", b =>
                {
                    b.Navigation("CropMonitorings");

                    b.Navigation("Harvests");

                    b.Navigation("PestCases");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farm", b =>
                {
                    b.Navigation("LandPlots");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Farmer", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.FieldVisit", b =>
                {
                    b.Navigation("VisitPhotos");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Harvest", b =>
                {
                    b.Navigation("CropListings");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.LandPlot", b =>
                {
                    b.Navigation("CropCycles");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.User", b =>
                {
                    b.Navigation("Buyers");

                    b.Navigation("Farmers");
                });

            modelBuilder.Entity("Smart_Farm_and_Crop_Yeild_Management_System.Models.YieldRecord", b =>
                {
                    b.Navigation("YieldPhotos");

                    b.Navigation("YieldValidations");
                });
#pragma warning restore 612, 618
        }
    }
}
